% Generate an iELVis/FreeSurfer-style stimulus + cortical surface figure.
%
% This script is intentionally MATLAB/iELVis based, matching the plotting
% approach in:
%   /Users/xialeihuang/Documents/MATLAB/electrode location/A06_generateSingleCombinedFigure.m
%
% Requirements:
%   1. MATLAB
%   2. FreeSurfer with fsaverage installed
%   3. iELVis toolbox on the MATLAB path
%   4. ROI coordinate/value CSV exported by Python
%
% Usage example:
%   matlab -nodisplay -r "roiCsv='.../roi_surface_points.csv'; outPng='.../ielvis_omni.png'; stimulusPng='.../stimulus.jpg'; run('scripts/generate_ielvis_roi_surface_figure.m'); exit"

if ~exist('roiCsv', 'var')
    error('roiCsv variable is required.');
end
if ~exist('outPng', 'var')
    error('outPng variable is required.');
end
if ~exist('stimulusPng', 'var')
    stimulusPng = '';
end
if ~exist('fsSubject', 'var')
    fsSubject = 'fsaverage';
end
if ~exist('viewName', 'var')
    viewName = 'omni';
end
if ~exist('surfType', 'var')
    surfType = 'inflated';
end
if ~exist('iELVisDir', 'var')
    iELVisDir = '/Users/xialeihuang/Documents/MATLAB/electrode location/iELVis-master/';
end

fshome = getenv('FREESURFER_HOME');
if isempty(fshome)
    error('FREESURFER_HOME is not set.');
end
fsmatlab = fullfile(fshome, 'matlab');
if exist(fsmatlab, 'dir')
    addpath(fsmatlab);
end
if exist(iELVisDir, 'dir')
    addpath(genpath(iELVisDir));
else
    error('iELVisDir does not exist: %s', iELVisDir);
end

subjects_dir = getenv('SUBJECTS_DIR');
if isempty(subjects_dir)
    setenv('SUBJECTS_DIR', fullfile(fshome, 'subjects'));
end

T = readtable(roiCsv);
requiredVars = {'x','y','z','isLeft','value'};
for i = 1:numel(requiredVars)
    if ~ismember(requiredVars{i}, T.Properties.VariableNames)
        error('Missing required column in roiCsv: %s', requiredVars{i});
    end
end

coords = [T.x, T.y, T.z];
isLeft = T.isLeft;
values = T.value;
values(~isfinite(values)) = 0;

% Positive hot overlay. Negative values are clipped because the report figure
% is intended to show red/yellow activation blobs like the reference image.
values = values - median(values, 'omitnan');
scale = prctile(abs(values), 95);
if scale <= 0 || ~isfinite(scale)
    scale = 1;
end
values = max(values ./ scale, 0);
values = min(values, 1);

cmap = hot(256);
colorIdx = max(1, min(256, round(values * 255) + 1));
colors = cmap(colorIdx, :);

cfg = [];
cfg.view = viewName;
cfg.surfType = surfType;
cfg.opaqueness = 0.35;
cfg.elecCoord = [coords, isLeft];
cfg.elecNames = cellstr("roi_" + string((1:height(T))'));
cfg.showLabels = 'n';
cfg.elecColors = colors;
cfg.elecColorScale = [0 1];
cfg.edgeBlack = 'n';
cfg.elecSize = 1.7;
cfg.elecShape = 'sphere';
cfg.pullOut = 1.2;
cfg.elecCbar = 'n';
cfg.title = [];

close all;
plotPialSurf(fsSubject, cfg);
drawnow;
pause(2);

fig = gcf;
set(fig, 'Color', 'white');
set(fig, 'Position', [100, 100, 1600, 950]);
set(fig, 'PaperPositionMode', 'auto');

if ~isempty(stimulusPng) && exist(stimulusPng, 'file')
    % Add a small stimulus panel in normalized figure coordinates.
    ax = axes('Position', [0.015 0.67 0.22 0.28]);
    imshow(imread(stimulusPng));
    title('stimulus', 'FontSize', 12);
end

sgtitle(sprintf('Stimulus-specific brain reaction (%s, %s)', fsSubject, viewName), ...
    'FontSize', 16, 'FontWeight', 'bold');

% Remove colorbars generated by iELVis internals.
delete(findobj(fig, 'Type', 'colorbar'));
delete(findobj(fig, 'Tag', 'Colorbar'));
drawnow;

print(fig, outPng, '-dpng', '-r500');
fprintf('Saved %s\n', outPng);
